# Generated by Django 4.2.4 on 2023-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_auto_20230812_2333"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="react",
            name="id",
        ),
        migrations.AlterField(
            model_name="react",
            name="employee",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
