# Generated by Django 4.2.4 on 2023-08-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_react_id_alter_react_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garbagetype",
            name="id",
        ),
        migrations.AddField(
            model_name="garbagetype",
            name="garbage_serial_number",
            field=models.AutoField(
                default="00000000", primary_key=True, serialize=False
            ),
        ),
    ]
